### ISSUE TITLE
Tray Toggle Buttons for Camera and Mic not Functioning Properly

### ISSUE THREAD

**Issue by ArturV93** [daily-co/react-native-daily-js-playground#6]
The toggle buttons for the camera and microphone in the Tray component are only functional once at the start of the video call session. Initially, the camera can be switched off and the microphone can be muted successfully. However, subsequent clicks on these buttons do not produce any action. For example, when attempting to turn the camera back on by clicking the camera toggle button again, no response is observed.

Steps to Reproduce:

Navigate to the video call page.

1. Click on the camera toggle button.
2. Observe the camera turning off successfully.
3. Click the camera toggle button again.
4. Notice that the camera does not turn back on, although it should.

Dependecies:
    "@daily-co/react-native-daily-js": "^0.50.0",
    "@daily-co/react-native-webrtc": "111.0.0-daily.2",
    "react-native": "^0.73.4",

**Comment by mattieruth** [comment]
Apologies for the delay. Thanks for reporting! We will look into this.

**Comment by ArturV93** [comment]
> Apologies for the delay. Thanks for reporting! We will look into this.

I got it working, but I'm unsure if it's the right way to do it. I made changes in the Tray.tsx file:

from:
`isCameraMuted = !localParticipant.video;
isMicMuted = !localParticipant.audio;   `

to:
`isCameraMuted = !localParticipant.tracks.video.track?._enabled;
isMicMuted = !localParticipant.tracks.audio.track?._enabled;`

It now works as expected

**Comment by mattieruth** [comment]
Thanks! That's very helpful. I've pushed a potential fix [here](https://github.com/daily-co/rn-daily-js-playground/pull/131) that i'm testing now.

**Comment by mattieruth** [comment]
I believe this should now be resolved.
